config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show] do
    # resources :users, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  resource :profile, only: [:show]

  namespace :profile do
    resources :places
    resources :bookings, only: [:index, :show]
  end
end

# /places/ index
# /places/:id show
# /places/:id/bookings/new
# /places/:id/bookings/:id
# /profile/places/new
# /profile
# /profile/places/

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availibility.rb
class Availibility < ApplicationRecord
  belongs_to :place, optional: :true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/place.rb
class Place < ApplicationRecord
  after_validation :geocode, if: :address_changed?
  geocoded_by :address

  belongs_to :user

   mount_uploader :photo, PhotoUploader

  has_many  :bookings, dependent: :destroy

  has_many  :availibilities, dependent: :destroy
  accepts_nested_attributes_for :availibilities, reject_if: :all_blank, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  # end 
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # skip_before_action :authenticate_user!
  before_action :set_place, only: [:new, :create]

  def new
    @booking = Booking.new
  end


  def create
    @booking = @place.bookings.build(booking_params)
    @booking.user = current_user
    @booking.save
    redirect_to profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:event_time, :status, :event_date)
    # t.references :place, foreign_key: true
    # t.references :user, foreign_key: true
  end

  def set_place
    @place = Place.find(params[:place_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @background = ["Germany_Hintersee_Lake.jpg", "Vietnam_Mu_Cang_Chai.jpg", "France_Mont_Saint_Michel.jpg"].sample
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_place, only: [:show]

  def index
    if params[:city].present?
      @places = Place.where("city ILIKE ?", "%#{params[:city].capitalize}%")
    else
      @places = Place.where.not(latitude: nil, longitude: nil)
    end

    if params[:event_date].present?
      @places = @places.joins(:availibilities).where(availibilities: { date: params[:event_date] })
    end

    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      # marker.infowindow render_to_string(partial: "/places/map_box", locals: { flat: flat })
    end
  end

  def show
    @alert_message = "You are viewing #{@place.name}"
    @place_coordinates = { lat: @place.latitude, lng: @place.longitude }
    @hash = Gmaps4rails.build_markers(@place) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

private

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/profile/bookings_controller.rb
class Profile::BookingsController < ApplicationController
  before_action :set_booking, only: [ :show, :create ]

  def index
    @booking = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

end

app/controllers/profile/places_controller.rb
class Profile::PlacesController < ApplicationController

  before_action :set_place, only: [:show, :update, :edit, :destroy]

  def show
  end

  def new
    @place = Place.new
  end

  def create
    new_params = place_params
    new_params[:city] = new_params[:city].capitalize
    @place = Place.new(new_params)
    @place.user = current_user

    # raise

    if @place.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @place.update(place_params)
    redirect_to profile_place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to profile_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :availibility, :city, :kind, :description, :photo, :photo_cache, :day_price, :night_price, :zip_code, :country, availibilities_attributes: [:id, :date, :_destroy])
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  # def show

  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="booking-new">
  <div class="info">
    <h1>Booking details</h1>

    <p> You want to go to :

      <%= @place.name %>
      and you will pay:
      <%= @place.day_price %>
    </p>


    <h3>When do you want to rent it ? </h3>
  </div>
  <%= form_for [@place, @booking] do |f| %>
  <%= f.label :event_date %>
  <%= f.text_field :event_date %>

  <%= f.label :event_time %>
  <%= f.text_field :event_time %>
  <div class="button">
    <%= f.submit "Cancel", :type => "reset", class:"btn btn-treehouse" %>
    <%= f.submit "Confirm", class:"btn btn-treehouse" %>
  </div>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>LibAIRty</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
<%= render 'partial/navbar' %>
<%= render 'devise/shared/flashes' %>

  <%= yield %>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
  <%= render 'partial/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image:url('<%= image_path @background %>')">

  <div class="banner-content text-center">
    <h1>libAIRty</h1>
    <p>Rent unique outside places</p>
    <%= form_tag("/places", method: "get") do %>
    <div class="content-form form-group" id="search_bar">
        <%= text_field_tag :city, nil, class:"home-search", placeholder: 'City' %>

        <%= date_field_tag :event_date, nil, class: "home-search" %>

        <%= submit_tag("submit", class:"search-btn navbar-wagon-item navbar-wagon-button btn") %>
    </div>
    <% end %>
    <!--     <a href="http://lmgtfy.com/?q=google" target="_blank" class=" btn btn-primary btn-lg">Get started</a> -->
  </div>
</div>

app/views/partial/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="#"></a><i class="fa fa-youtube"></i></li>
          <li><a href="#"></a><i class="fa fa-instagram"></i></li>
          <li><a href="#"></a><i class="fa fa-facebook"></i></li>
          <li><a href="#"></a><i class="fa fa-twitter"></i></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <br>
        <p>Take a walk on the green side</p>
      </div>
    </div>
  </div>
</div>

app/views/partial/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class:"navbar-wagon-brand" do  %>
  <%= image_tag 'leaf.jpg', class: "avatar"  %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->


    <!-- Text link -->


    <!-- Notification link-->
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue"></div>
      </div>
    </a> -->



    <!-- Profile picture and dropdown -->
    <% if signed_in? %>
    <div class="navbar-wagon-item">

      <div class="dropdown">
        <span>
          <%= link_to 'Rent your place', new_profile_place_path, class: "search-btn navbar-wagon-item navbar-wagon-button", style: "color: white"  %></span>
          <span>
            <%=link_to current_user.first_name, profile_path %>
            <%=link_to current_user.last_name, profile_path %>
          </span>
          <% if current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class:"avatar", data: { toggle: 'dropdown'} %>


          <% else %>
          <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>

          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>  <%= link_to 'Profile', profile_path %>
              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div>
        </div>
        <% else %>
        <%= link_to 'login', new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
        <%= link_to "Become a land lord", new_user_registration_path,  class: "navbar-wagon-item navbar-wagon-button btn" %>
        <% end %>

        <!-- Button (call-to-action) -->

      </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>  <%= link_to 'Profile', profile_path %>
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    </div>

app/views/places/index.html.erb
<div class="wrapper-grey padded">
  <h2 class="text-center">Your next trip</h2>

  <div class="container">
    <div class="row">
    <% if @places.empty? %>
    <h3>GAME OVER</h3>
    <%= link_to 'Try again', root_path %>
    <% else %>
    <% @places.each do |place| %>
      <div class="col-xs-12 col-sm-4">

          <%= link_to place_path(place), class: "card-link" do %>
        <div class="card" id="paris" style="background-image: url('<%= place.photo.present? ? place.photo : image_path('sky.jpg') %>')" >
          <div class="card-category">
            <%= place.city %> 
          </div>
          <div class="card-description">
            <h2><%= place.name %></h2>
            <p><%= place.kind%> / <%= place.day_price%></p>
          </div>
          <div class="card-user avatar avatar-small">
              <% if place.user.facebook_picture_url %>
                <%= image_tag place.user.facebook_picture_url, class: "avatar" %>
              <% else %>
                <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>
              <% end %>
          </div>
          <!-- <a class="card-link" href="#"></a> -->
        </div>
        <% end %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

<div id="map" style="width: 100%; height: 500px"></div>

<% content_for(:after_js) do %>
<%= javascript_tag do %>

$(document).on('ready', function() {
var handler = Gmaps.build('Google');
handler.buildMap({provider: { scrollwheel: false, zoomControl: false }, internal: { id: 'map' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});
<% end %>
<% end %>

app/views/places/show.html.erb
<div class="media">
  <div class="media-body">
    <div class="media-section ">
     <%= cl_image_tag @place.photo %>
     <h2> <%= @place.description %></h2>

     <!-- <img src="https://images.unsplash.com/photo-1418479631014-8cbf89db3431?dpr=1&amp;auto=format&amp;crop=entropy&amp;fit=crop&amp;w=1500&amp;h=1000&amp;q=80&amp;cs=tinysrgb" alt> -->
   </div>
    <!-- <div class="media-section">
      <h2>Description</h2>
      ...
    </div> -->

    <div class="media-aside">
     <h3>Address: </h3> <%= @place.address%>
     <hr>
     <p><h3>City: </h3><%= @place.city%></p>
     <hr>
     <p><h3>Kind: </h3><%= @place.kind%></p>
     <hr>
   </div>

 </div>
 <div class="media-aside">
  <div class="media-section text-center">

    <h2><%= @place.name.capitalize %></h2>

    <p>
      <%= @place.day_price %>  <span class="glyphicon glyphicon-eur" aria-hidden="true"></span> per day
    </p>

    <% if @place.user.facebook_picture_url %>
    <%= image_tag @place.user.facebook_picture_url, class: "avatar-large" %>


    <% else %>
    <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>

    <% end %>
    <div class="name-attributes">
      <%= @place.user.first_name %>
      <%= @place.user.last_name %>
    </div>

  </div>
  <div class="media-section text-center">
    <p><%= link_to 'Book', new_place_booking_path(@place), class: "navbar-wagon-button btn" %></p>

  </div>
  <div>
    <div id="map" style="width: 100%; height: 300px;"></div>
      <% content_for(:after_js) do %>
      <%= javascript_tag do %>
      $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({provider: { scrollwheel: false, zoomControl: false }, internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
      handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
      }
      });
      });
      <% end %>
      <% end %>
  </div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="show-background"></div>
<div class="padded">
  <div class="profile-header-wrapper">
    <div class="profile-header-container text-center">
      <div class="profile-header-infos">

        <% if current_user.facebook_picture_url %>
        <%= image_tag current_user.facebook_picture_url, class:"avatar-large", data: { toggle: 'dropdown'} %>
        <% else %>
        <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>
        <% end %>
        <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
      </div>


      <div class="tabs">
        <a class="tab active" data-target="#spots">
          <p>Manage</p>
          <h3>Your spots</h3>
        </a>
        <a class="middle_tab tab" data-target="#guests">
          <p>Manage</p>
          <h3>Your guests</h3>
        </a>
        <a class="tab" data-target="#bookings">
          <p>Manage</p>
          <h3>Your bookings</h3>
        </a>
      </div>
    </div>
  </div>

  <div class="background-green">
    <div class="tab-content" id="spots">
      <div class='product-body'>
        <% current_user.places.each do |place| %>
        <h2>
          <%= place.name.capitalize %>

        </h2>
        <div class="products">
          <div class="name_image">
            <%= cl_image_tag place.photo, height: 120, width: 120, crop: :fill%>
            <ul class="list-inline product-controls">
              <li><%= link_to 'see details', profile_place_path(place), style: "btn-medium"  %></li>
              <li> <%= link_to edit_profile_place_path(place), method: :get, data: { confirm: 'Are you sure you want to edit this place?'} do %>
               <i class="fa fa-pencil"></i>
               <% end %>
             </li>
             <li>  <%= link_to profile_place_path(place), method: :delete, data: { confirm: 'Are you sure you want to delete this place?'} do %>
              <i class="fa fa-trash-o"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>



<div class="background-green">
  <div class="tab-content hidden" id="guests">
    <div class='product-body'>

      <% current_user.places.reverse.each do |place| %>
      <h2>
        <%= place.name %>
      </h2>
      <div class="products">
        <% if place.bookings.blank? %>
        <h4> <%= "You don't have any guest for this spot." %> </h4>

        <%else %>
        <% place.bookings.each do |booking| %>
        <%= booking.event_date %>
        <%= booking.user.first_name %>
        <%= booking.user.last_name %>

        <% end %>
        <% end %>
      </div>
      <%end %>
    </div>

  </div>
</div>


<div class="background-green">
  <div class="tab-content hidden" id="bookings">
    <div class="product-body">
      <% current_user.bookings.each do |booking| %>
      <h2> Don't forget :
        <%= booking.event_date %> at
        <%= booking.event_time %>
      </h2>
      <div class="products">
        <p>Where: <%= booking.place.name%> </p>
        <p>Address: <%= booking.place.address %></p>
        <p>Your Host: <%= booking.place.user.first_name %>
          <%= booking.place.user.last_name %> </p>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>